Documentation fix in AboutCsvCmdlets and code fix in AboutXml to fix XML file load issue.
vexx32/PSKoans pull request #425
Opened 2021-02-15 15:25 UTC by dgoldman-msft

# PR Summary

## Context

## Changes

## Checklist

- [X ] Pull Request has a meaningful title.
- [X ] Summarized changes.
- [X] Pull Request is ready to merge & is not WIP.
- [ ] Added tests / only testable interactively.
  - Make sure you add a new test if old tests do not effectively test the code changed.
- [ ] Added documentation / opened issue to track adding documentation at a later date.

2021-02-15 15:30 UTC, indented-automation requested changes

2021-02-15 15:30 UTC, indented-automation commented on PSKoans/Koans/Cmdlets 2/AboutCsvCmdlets.Koans.ps1
> +			# Make sure to change the delimiter below
4-space indentation please.
```suggestion
            # Make sure to change the delimiter below
```

2021-02-15 15:30 UTC, indented-automation commented on PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1
> +	}
4-space indentation please.
```suggestion
    BeforeAll {
        $path = Join-Path -Path $TestDrive -ChildPath document.xml
    }
```
Which `It` is this specifically addressing? `$path` is re-used a great deal. If this is being added to BeforeAll the individual entries should be purged?

2021-02-15 15:34 UTC, dgoldman-msft commented on PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1
> +	}
I was debugging an issue where running Show-Karma and without the BeforeAll statement we would hit line 42 and run the following code and replace the live file breaking the Kona test. Joel had me test that code implementation just for this file which fixes the problem. I could run a test purging the other Join-Paths to see if they are needed. Joel didn't mention at the time of implementation.

 Set-Content -Path $path -Value @'
<documentRoot>
    <element>A short XML file</element>
</documentRoot>
'@

2021-02-15 15:41 UTC, indented-automation commented on PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1
> +	}
I wrote the topic, I wouldn't necessarily expect Joel to know it :)

Can you show me how to re-produce the issue? The file is rewritten many times during the topic but should only matter within a single `It`.

2021-02-15 15:47 UTC, indented-automation commented on PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1
> +	}
Okay, got it. It actually needs the line inserting at the start of `is much faster to use the Load method of XmlDocument for large files` (was line 54). That's where the bug is.

Of course, the alternative is to keep the BeforeAll as you have above. In which case the extraneous `$path = ` statements should be removed.

2021-02-15 15:49 UTC, dgoldman-msft commented
That makes sense 😊 I am able to reproduce live on my system if I remove the BeforeAll statement. What will happen is the following:


  1.  Open Code and load up the AboutXML.ps1
  2.  In PS or Windows Terminal run: Show-Karma -topic AboutXML or Show-Karma

Expected result is to have a successful test run.
Actual result :  The AboutXml.ps1 file is changed on the fly to just the set-content from like 41 breaking the show-karma.

[00:03:58] (8) ..\0.67.1\public> show-karma
Invoke-Koan : No modules were removed. Verify that the specification of modules to remove is correct and those modules
exist in the runspace. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Koan], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Invoke-Koan

Invoke-Koan : No modules were removed. Verify that the specification of modules to remove is correct and those modules
exist in the runspace. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Koan], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Invoke-Koan

Invoke-Koan : Cannot find drive. A drive with the name 'TestDrive' does not exist. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TestDrive:String) [New-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand
    + PSComputerName        : localhost

Invoke-Koan : The term 'console-write' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (console-write:String) [Invoke-Koan], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

Invoke-Koan : Cannot find drive. A drive with the name 'TestDrive' does not exist. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (TestDrive:String) [New-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand
    + PSComputerName        : localhost

Invoke-Koan : The term 'console-write' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At C:\Users\sifu1\OneDrive\Documents\WindowsPowerShell\Modules\pskoans\0.67.1\Public\Get-Karma.ps1:111 char:32
+                 $PesterTests = Invoke-Koan @{
+                                ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (console-write:String) [Invoke-Koan], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

I was able to track this down through debugging and then reached out to Joel. Do you not have the same issue? Subsequently I just ran a test the removal of all the other Join-Paths and this also works for a success test run.

Thanks
Dave

From: Chris Dent <notifications@github.com>
Sent: Monday, February 15, 2021 10:42 AM
To: vexx32/PSKoans <PSKoans@noreply.github.com>
Cc: Dave <dgoldman@dgoldman.org>; Author <author@noreply.github.com>
Subject: Re: [vexx32/PSKoans] Documentation fix in AboutCsvCmdlets and code fix in AboutXml to fix XML file load issue. (#425)


@indented-automation commented on this pull request.

________________________________

In PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1<https://github.com/vexx32/PSKoans/pull/425#discussion_r576278404>:

> +     BeforeAll      {

+              $path = Join-Path $TestDrive -ChildPath document.xml

+       }

I wrote the topic, I wouldn't necessarily expect Joel to know it :)

Can you show me how to re-produce the issue? The file is rewritten many times during the topic but should only matter within a single It.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/vexx32/PSKoans/pull/425#discussion_r576278404>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJQPRPC4AJCDX7RHHKFQN7DS7E6C3ANCNFSM4XU3ZONA>.

2021-02-18 15:35 UTC, vexx32 requested changes
Looks good to me, with one whitespacing thing to sort out before we merge. 🙂

2021-02-18 15:35 UTC, vexx32 commented on PSKoans/Koans/Constructs and Patterns/AboutXml.Koans.ps1
> +	}
Looks like we're using tab spacing here at the moment? Spaces only please, finding stray whitespace can be a pain later.

2021-02-19 13:47 UTC, vexx32 approved these changes
Thanks! 😁

2021-02-19 13:47 UTC, merged